Repository acm-ucr/wushu-website, pull requests merged in 2025-05, with the labels that each got.

#43 Mapping through board
  src/app/board/page.tsx
  src/components/board/BoardMemberCard.tsx
  src/components/board/BoardMemberMap.tsx
  src/data/BoardMembers.ts
Labels: Ready For Review

#62 Responsified navbar
  package-lock.json
  package.json
  src/components/Navbar.tsx
Labels: Ready For Review

#49 Trying to fix staged files for Who We Are
  src/components/home/WhoWeAre.tsx
Labels: Ready For Review, Address Comments

#53 Trying to fix staged files Location and Time
  src/components/home/LocationAndTime.tsx
Labels: Ready For Review, Address Comments

#64 Fixed Meet The Board Font
  src/app/globals.css
  src/app/page.tsx
  src/components/board/MeetTheBoard.tsx
Labels: Address Comments

#67 Footer Mobile Responsiveness
  public/logos/goldcorners.svg
  src/components/Footer.tsx
Labels: Ready For Review

#83 Email Text Update
  src/components/contact/WantToBookUs.tsx
Labels: Ready For Review

#78 Tried to do Who We Are Responsiveness
  src/components/home/WhoWeAre.tsx
Labels: Ready For Review

#80 Added mobile responsiveness to Performances Component
  src/components/performances/Performance.tsx
Labels: Ready For Review

#82 Finished Contact Us Mobile Responsive
  src/app/page.tsx
  src/components/contact/ContactUs.tsx
Labels: Ready For Review

#85 Finished HowToJoin Component
  src/components/home/JoinForm.tsx
  src/components/performances/Performance.tsx
Labels: Ready For Review

#99 Responsify Join Form
  src/components/home/JoinForm.tsx
Labels: help wanted, Ready For Review

#100 Created Gallery page
  src/app/gallery/page.tsx
Labels: Ready For Review

#111 Responsified BoardMemberCard and mapping
  src/components/board/BoardMemberCard.tsx
  src/components/board/BoardMemberMap.tsx
Labels: Ready For Review

#112 Responsify WantToBookUs
  src/components/contact/WantToBookUs.tsx
Labels: Ready For Review
